### ISSUE TITLE
Suggestion for streaming client (README)

### ISSUE THREAD

**Issue by Fleker** [klaxa/mkvserver_mk2#29]
Instead of `-c libx264` use [`-codec:v libx264`](https://superuser.com/questions/893086/unknown-encoder-x264-in-ffmpeg-despite-following-proper-installation-instructi).

**Comment by klaxa** [comment]
Hi,
using -c instead of -c:v or -codec:v forces the specified codec on all streams. This is very useful for the copy pseudo-codec. In the example created in the readme there is only one video stream without audio or anything else, therefore forcing libx264 on all streams will only apply to the video stream anyway. However, I agree that for clarity and copy-paste's sake it's safer to specify -c:v.
