### ISSUE TITLE
Embed Stream

### ISSUE THREAD

**Issue by jb-alvarado** [klaxa/mkvserver_mk2#5]
Hello,
I have try you server, and with vlc and ffplay I'm able to play the stream. But I would like to embed the stream to. Is this possible?, with something like this:

```
<video id="myStream" class="video-js">
      <source src="http://192.168.0.91:8080" type="application/x-mpegURL">
</video>
```

**Comment by klaxa** [comment]
Once browsers support the matroska format, maybe. As of now, this does not work and there are currently no plans to support this. (Sorry, but video in the browser is garbage imho anyway.)
(It may work if you tweak the program to produce webm instead of matroska and feed it a vp8/vorbis or vp9/opus file. I have not tested this.)
